version: '3.8'

services:

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl
    depends_on:
      web-ui:
        condition: service_healthy
      web-api:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s

  web-api:
    container_name: web-api
    build: ./web-api/.
    expose:
      - 8000
    env_file:
      - ./web-api/.env
    environment:
      - PORT=8000
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-O",
          "/dev/null",
          "http://web-api:8000/healthz"
        ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s

  web-ui:
    container_name: web-ui
    build: ./web-ui/.
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://web-ui" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s
