on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Set Version
        id: version
        run: >
          echo "version=$(cat ${{ github.workspace }}/${{ inputs.service_name }}/version.txt).${{ github.run_number }}"
          >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.service_name }}
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/\
            playground-app-${{ inputs.service_name }}:\
            ${{ github.head_ref || github.ref_name }}-v${{ steps.version.outputs.version }}"
