on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      -
        name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email github-actions@github.com
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Patch Version
        run: >
          echo "$(cat ${{ github.workspace }}/${{ inputs.service_name }}/version.txt).${{ github.run_number }}"
          > ${{ github.workspace }}/${{ inputs.service_name }}/version.txt
      -
        name: Use Version
        id: version
        run: >
          echo "version=$(cat ${{ github.workspace }}/${{ inputs.service_name }}/version.txt)"
          >> $GITHUB_OUTPUT
      -
        name: Set Image Tag (main branch)
        id: main_tag
        run: >
          echo "tag=v${{ steps.version.outputs.version }}" >> $GITHUB_OUTPUT
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      -
        name: Set Image Tag (feature branch)
        id: feature_tag
        run: >
          echo "tag=${{ github.head_ref || github.ref_name }}" >> $GITHUB_OUTPUT
        if: github.ref != 'refs/heads/main' || github.event_name == 'pull_request'
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.service_name }}
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/\
            playground-app-${{ inputs.service_name }}:\
            ${{ steps.main_tag.outputs.tag || steps.feature_tag.outputs.tag }}"
      -
        name: Create Git Tag
        run: |
          git tag ${{ steps.main_tag.outputs.tag }}
          git push origin ${{ steps.main_tag.outputs.tag }}
        if: ${{ steps.main_tag.outputs.tag }}
      -
        name: Checkout Deployment Configuration
        uses: actions/checkout@v4
        with:
          repository: dfal/playground-deployment
          path: deployment
        if: ${{ steps.main_tag.outputs.tag }}
      -
        name: Update Deployment Configuration (Dev)
        working-directory: deployment
        run: |
          sed -i "s/-${{ inputs.service_name }}:.*\"/-${{ inputs.service_name }}:${{ steps.main_tag.outputs.tag }}\"/" ./environmets/dev/values.yaml
          cat ./environmets/dev/values.yaml
        if: ${{ steps.main_tag.outputs.tag }}
      -
        name: Commit Deployment Configuration (Dev)
        working-directory: deployment
        run: |
          git add .
          git commit -m "CI generated"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PAT }}
        if: ${{ steps.main_tag.outputs.tag }}
