name: WEB-UI CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - web-ui/**
  pull_request:
    branches: [ "main" ]
    paths:
      - web-ui/**

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/common-jobs.yaml
    permissions: write-all
    with:
      service_name: web-ui
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
