name: WEB-API CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - web-api/**
  pull_request:
    branches: [ "main" ]
    paths:
      - web-api/**

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/common-jobs.yaml
    permissions: write-all
    with:
      service_name: web-api
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      CI_PAT: ${{ secrets.CI_PAT }}

