name: WEB-API CI

on:
  push:
    branches: [ "main" ]
    paths:
      - web-api/**
  pull_request:
    branches: [ "main" ]
    paths:
      - web-api/**
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/playground-app/web-api:${{ env.GITHUB_HEAD_REF == "main" && "latest" || env.GITHUB_HEAD_REF}}
